---
- name: Create ArgoCD application for nodeset
  include_role:
    name: argocd
    tasks_from: application
  vars:
    argocd_app_name: edpm-nodeset
    argocd_app_path: examples/dt/perfscale/scalelab/edpm/nodeset
    argocd_wait_timeout: 600

- name: Create ArgoCD application for dataplane deployment
  include_role:
    name: argocd
    tasks_from: application
  vars:
    argocd_app_name: edpm-deployment
    argocd_app_path: examples/dt/perfscale/scalelab/edpm/deployment
    argocd_wait_timeout: 2400

- name: Run nova-manage cell_v2 discover_hosts
  shell: |
    oc project openstack
    oc rsh nova-cell0-conductor-0 nova-manage cell_v2 discover_hosts --verbose

- name: List OpenStack hypervisors
  shell: |
    oc project openstack
    oc rsh openstackclient openstack hypervisor list
  register: hypervisor_output

- name: Display hypervisor list
  debug:
    msg: "{{ hypervisor_output.stdout_lines }}"

