---
- name: Create ArgoCD application for OLM operators
  ansible.builtin.include_role:
    name: argocd
    tasks_from: application
  vars:
    argocd_app_name: common-olm
    argocd_app_path: examples/common/olm
    argocd_wait_timeout: 600

- name: Create ArgoCD application for MetalLB
  ansible.builtin.include_role:
    name: argocd
    tasks_from: application
  vars:
    argocd_app_name: common-metallb
    argocd_app_path: examples/common/metallb
    argocd_wait_timeout: 600

- name: Create ArgoCD application for NMState
  ansible.builtin.include_role:
    name: argocd
    tasks_from: application
  vars:
    argocd_app_name: common-nmstate
    argocd_app_path: examples/common/nmstate
    argocd_wait_timeout: 600

- name: Create ArgoCD application for OpenStack operators
  ansible.builtin.include_role:
    name: argocd
    tasks_from: application
  vars:
    argocd_app_name: common-openstack
    argocd_app_path: examples/common/openstack
    argocd_wait_timeout: 600
