---
- name: Create ArgoCD application for LVMS operator
  ansible.builtin.include_role:
    name: argocd
    tasks_from: application
  vars:
    argocd_app_name: lvms-operator
    argocd_app_path: examples/dt/perfscale/scalelab/lvms
    argocd_app_namespace: openshift-storage
    argocd_wait_timeout: 1200

- name: Create ArgoCD application for LVM cluster
  ansible.builtin.include_role:
    name: argocd
    tasks_from: application
  vars:
    argocd_app_name: lvms-cluster
    argocd_app_path: examples/dt/perfscale/scalelab/lvms/lvm-cluster
    argocd_app_namespace: openshift-storage
    argocd_wait_timeout: 900
