---
- name: Create ArgoCD application for NNCP
  include_role:
    name: argocd
    tasks_from: application
  vars:
    argocd_app_name: nncp
    argocd_app_path: examples/dt/perfscale/scalelab/networking/nncp
    argocd_wait_timeout: 300

- name: Create ArgoCD application for network CRs
  include_role:
    name: argocd
    tasks_from: application
  vars:
    argocd_app_name: network
    argocd_app_path: examples/dt/perfscale/scalelab/networking
    argocd_wait_timeout: 300

- name: Create ArgoCD application for controlplane
  include_role:
    name: argocd
    tasks_from: application
  vars:
    argocd_app_name: controlplane
    argocd_app_path: examples/dt/perfscale/scalelab
    argocd_wait_timeout: 600
